apiVersion: v1
kind: ConfigMap

metadata:
  name: mysql
  namespace: roboshop
data:
  my.cnf: |
    [mysqld]
    innodb_redo_log_capacity = 2G

---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    component: mysql
    tier: db
  
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: mysql
      tier: db

  template:
    metadata:
      labels:
        project: roboshop
        component: mysql
        tier: db
      
    spec:
      containers:
      - name: mysql
        image: vikasvanamala/mysql:v1
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 20
          periodSeconds: 20
        volumeMounts:
        - name: mysql-config
          mountPath: /etc/mysql/conf.d/my.cnf
          subPath: my.cnf
      
      volumes:
      - name: mysql-config
        configMap:
          name: mysql

---
apiVersion: v1
kind: Service

metadata:
  name: mysql
  namespace: roboshop

spec:
  selector:
    project: roboshop
    component: mysql
    tier: db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306






